let allMusic = [
  {
    name: "粉色海洋",
    artist: "周杰伦",
    img: "music-1",
    src: "music-1",
  },
  {
    name: "Mojito",
    artist: "周杰伦",
    img: "music-2",
    src: "music-2",
  },
  {
    name: "七里香",
    artist: "周杰伦",
    img: "music-3",
    src: "music-3",
  },
  {
    name: "兰亭序",
    artist: "周杰伦",
    img: "music-4",
    src: "music-4",
  },
  {
    name: "听妈妈的话",
    artist: "周杰伦",
    img: "music-5",
    src: "music-5",
  },
  {
    name: "告白气球",
    artist: "周杰伦",
    img: "music-6",
    src: "music-6",
  },
  {
    name: "园游会",
    artist: "周杰伦",
    img: "music-7",
    src: "music-7",
  },
  {
    name: "晴天",
    artist: "周杰伦",
    img: "music-8",
    src: "music-8",
  },
  {
    name: "牛仔很忙",
    artist: "周杰伦",
    img: "music-9",
    src: "music-9",
  },
  {
    name: "稻香",
    artist: "周杰伦",
    img: "music-10",
    src: "music-10",
  },
  {
    name: "我要夏天",
    artist: "周杰伦",
    img: "music-11",
    src: "music-11",
  },
  {
    name: "花海",
    artist: "周杰伦",
    img: "music-12",
    src: "music-12",
  },
  {
    name: "阳光宅男",
    artist: "周杰伦",
    img: "music-13",
    src: "music-13",
  },
];
